name: Registry BG Tasks Celery Beat Branch Workflow

on:
  push:
    branches-ignore:
      - develop
    tags-ignore:
      - '*'

jobs:
  docker-build-for-branch:
    name: Docker Build and Push For Celery Beat Branch
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ secrets.docker_hub_organisation || 'openg2p' }}
      SERVICE_NAME: openg2p-registry-celery-beat-producers
    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')

          IMAGE_ID=$NAMESPACE/$SERVICE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$BRANCH_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo IMAGE_ID=$IMAGE_ID >> $GITHUB_ENV
          echo VERSION=$VERSION >> $GITHUB_ENV

          docker build ./openg2p-registry-celery-beat-producers -f ./openg2p-sr-celery-beat-producers/Dockerfile-git \
            --tag $IMAGE_ID:$VERSION
          if [[ '${{ secrets.docker_hub_token }}' != '' && '${{ secrets.docker_hub_actor }}' != '' ]]; then
            export DOCKER_PUSH="true"
            echo DOCKER_PUSH=$DOCKER_PUSH >> $GITHUB_ENV
          fi
      - name: Docker push
        if: env.DOCKER_PUSH == 'true'
        run: |
          echo "${{ secrets.docker_hub_token }}" | docker login -u ${{ secrets.docker_hub_actor }} --password-stdin
          docker push ${{ env.IMAGE_ID }}:${{ env.VERSION }}
